### ISSUE TITLE
Unable to save PDF

### ISSUE THREAD

**Issue by dantomdarienzo** [naturalcrit/homebrewery#1587]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by G-Ambatte** [comment]
This sounds like the Google credentials have expired, which happens one year after the last sign in via Google.

The fix for this is to head to https://www.naturalcrit.com/login and click logout if present (in small text at the bottom of the page), then click "Sign In with Google" which will refresh the Google credentials. If this was the source of the issue, it should now be resolved and it should not return for at least twelve months.

Logout location:
![image](https://user-images.githubusercontent.com/19826659/129470020-8a43b435-5189-46bc-8f66-a27b226c3b62.png)

---

If following these steps does not resolve the issue, please let us know!

**Comment by dantomdarienzo** [comment]
I've tried this but it didn't solve the issue, the error is the same as before:
```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Are you able to create and save a new brew to google drive?

**Comment by dantomdarienzo** [comment]
Yes, I think it's solved now.

It seems the issue was that I initially didn't connect my Google Drive account to the Homebrewery account, after doing that, logging out an logging in again, I was able to save the brew.

**Comment by calculuschild** [comment]
Hey @dantomdarienzo , just to make sure we know how to help people in the future with this problem, do you mind clarifying what happened here?

Earlier you said you tried the steps of logging out and back in with Google, which should have linked your account to Google if it wasn't already. However you said that didn't work. What different step did you take in the end that linked your account to Google if it wasn't already?

**Comment by dantomdarienzo** [comment]
The issue was I signed up with my Google account, but didn't give permission to Homebrewery to access to my Drive account.

What I did was:

- Log out
- Log in again using my Google account
- Give permission to Homebrewery to access my Google Drive account and continue

After logging in, it was automatically saving brews to my Drive account and I was able to transfer them to my Homebrewery account.
